### ISSUE TITLE
Errors due to React package deprecation

### ISSUE THREAD

**Issue by AnthonyLamot** [okgrow/accounts-ui-react#10]
This package still seems to use two deprecated React functions. Can it be upgraded?

The errors I'm getting are: 

1. Warning: Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
2. Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class

**Comment by cfnelson** [comment]
@AnthonyLamot Closing to keep the discussion in one place. Track the status of the issue https://github.com/okgrow/accounts-ui-react/issues/8
